{"stats": {"errors": 0, "failures": 1, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:S256Test", "name": "test_address", "time": 0.07258820533752441, "type": "failure", "errtype": "builtins.AssertionError", "message": "'1UktUiQ3bjqYR9ZMREGwGrHmhuqp' != '148dY81A9BmdpMhvYEVznrM45kWN32vSCN'\n- 1UktUiQ3bjqYR9ZMREGwGrHmhuqp\n+ 148dY81A9BmdpMhvYEVznrM45kWN32vSCN\n", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/pb-tester-ccdle12/addresses-from-keys-jsong-pb-sf-072618/test/index_test.py\", line 17, in test_address\n    point.address(compressed=True, testnet=False), mainnet_address)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 1203, in assertMultiLineEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 670, in fail\n    raise self.failureException(msg)\nAssertionError: '1UktUiQ3bjqYR9ZMREGwGrHmhuqp' != '148dY81A9BmdpMhvYEVznrM45kWN32vSCN'\n- 1UktUiQ3bjqYR9ZMREGwGrHmhuqp\n+ 148dY81A9BmdpMhvYEVznrM45kWN32vSCN\n\n"}]}